package com.schwab.nms.database.entities.enums;

public enum AuditEventType {

    NOTIFICATION_ACCEPTED,
    NOTIFICATION_REJECTED,
    NOTIFICATION_DUPLICATE_SUPPRESSED,
    ROUTING_STARTED,
    NOTIFICATION_QUEUED,
    DELIVERY_ATTEMPTED,
    DELIVERY_SUCCEEDED,
    DELIVERY_FAILED,
    NOTIFICATION_EXPIRED,
    RETRY_SCHEDULED
}